"""API router package. Routers are listed explicitly in app.main."""

from app.api.routers import (
    agents,
    analytics,
    assets,
    categories,
    compliance,
    daily_production,
    health,
    ideas,
    library,
    metadata,
    notifications,
    opportunities,
    opportunity_fusion,
    personal_performance,
    private,
    production,
    prompt_packs,
    prompts,
    recommendations,
    settings,
    similarity,
    sources,
    submissions,
    trends,
)

__all__ = [
    "agents",
    "analytics",
    "assets",
    "categories",
    "compliance",
    "daily_production",
    "health",
    "ideas",
    "library",
    "metadata",
    "notifications",
    "opportunities",
    "opportunity_fusion",
    "personal_performance",
    "private",
    "production",
    "prompt_packs",
    "prompts",
    "recommendations",
    "settings",
    "similarity",
    "sources",
    "submissions",
    "trends",
]
