"""Provenance detection covers text, JSON, and tool markers."""

from __future__ import annotations

from types import SimpleNamespace

from app.schemas.common import resolve_provenance
from app.schemas.enums import DataProvenance


def test_text_marker_change_summary():
    row = SimpleNamespace(change_summary="demo seed version", parameters={})
    assert resolve_provenance(row) == DataProvenance.MOCK


def test_text_marker_explanation():
    row = SimpleNamespace(explanation="DEMO rule evaluation", parameters={})
    assert resolve_provenance(row) == DataProvenance.MOCK


def test_json_marker_in_parameters():
    row = SimpleNamespace(
        change_summary="refined",
        parameters={"tool": "mock-generator", "seed": 42},
    )
    assert resolve_provenance(row) == DataProvenance.MOCK


def test_json_nested_marker():
    row = SimpleNamespace(
        parameters={"nested": {"note": "generated by demo pipeline"}},
    )
    assert resolve_provenance(row) == DataProvenance.MOCK


def test_no_marker_returns_none():
    row = SimpleNamespace(
        change_summary="human edit",
        parameters={"tool": "photoshop"},
    )
    assert resolve_provenance(row) is None


def test_data_provenance_column_wins():
    row = SimpleNamespace(
        data_provenance=DataProvenance.USER_PROVIDED,
        change_summary="demo text that must not override",
    )
    assert resolve_provenance(row) == DataProvenance.USER_PROVIDED
