"""Shared agent helpers: structured logging + mock labeling."""

from __future__ import annotations

from sqlalchemy.orm import Session

from app.models.platform import AgentLog, AgentRun
from app.schemas.enums import AgentLogLevel

MOCK_NOTE = "Output generated by mock providers (MOCK) — not real market data."


def log(
    db: Session, run: AgentRun, level: AgentLogLevel, message: str, context: dict | None = None
) -> None:
    db.add(AgentLog(agent_run_id=run.id, level=level, message=message, context=context or {}))
    db.flush()


def info(db: Session, run: AgentRun, message: str, context: dict | None = None) -> None:
    log(db, run, AgentLogLevel.INFO, message, context)


def warn(db: Session, run: AgentRun, message: str, context: dict | None = None) -> None:
    log(db, run, AgentLogLevel.WARNING, message, context)
